apiVersion: v1
kind: Secret
metadata:
  name: {{ template "fullname" . }}
type: Opaque
data:
  cert.pem: {{ (default "TUlTU0lORw==" .Values.env.apiserverCert) | quote }}
  key.pem: {{ (default "TUlTU0lORw==" .Values.env.apiserverKey) | quote }}
  clientSecret: {{ default "" .Values.env.azureClientKey | b64enc | quote }}
