package eci

//Licensed under the Apache License, Version 2.0 (the "License");
//you may not use this file except in compliance with the License.
//You may obtain a copy of the License at
//
//http://www.apache.org/licenses/LICENSE-2.0
//
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.
//
// Code generated by Alibaba Cloud SDK Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

// ContainerGroup is a nested struct in eci response
type ContainerGroup struct {
	ContainerGroupId   string      `json:"ContainerGroupId" xml:"ContainerGroupId"`
	ContainerGroupName string      `json:"ContainerGroupName" xml:"ContainerGroupName"`
	RegionId           string      `json:"RegionId" xml:"RegionId"`
	ZoneId             string      `json:"ZoneId" xml:"ZoneId"`
	Memory             float64     `json:"Memory" xml:"Memory"`
	Cpu                float64     `json:"Cpu" xml:"Cpu"`
	VSwitchId          string      `json:"VSwitchId" xml:"VSwitchId"`
	SecurityGroupId    string      `json:"SecurityGroupId" xml:"SecurityGroupId"`
	RestartPolicy      string      `json:"RestartPolicy" xml:"RestartPolicy"`
	IntranetIp         string      `json:"IntranetIp" xml:"IntranetIp"`
	Status             string      `json:"Status" xml:"Status"`
	InternetIp         string      `json:"InternetIp" xml:"InternetIp"`
	CreationTime       string      `json:"CreationTime" xml:"CreationTime"`
	SucceededTime      string      `json:"SucceededTime" xml:"SucceededTime"`
	Tags               []Tag       `json:"Tags" xml:"Tags"`
	Events             []Event     `json:"Events" xml:"Events"`
	Containers         []Container `json:"Containers" xml:"Containers"`
	Volumes            []Volume    `json:"Volumes" xml:"Volumes"`
}
