package eci

import "github.com/aliyun/alibaba-cloud-sdk-go/sdk/requests"

//Licensed under the Apache License, Version 2.0 (the "License");
//you may not use this file except in compliance with the License.
//You may obtain a copy of the License at
//
//http://www.apache.org/licenses/LICENSE-2.0
//
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.
//
// Code generated by Alibaba Cloud SDK Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

// Volume is a nested struct in eci response
const (
	VOL_TYPE_NFS              = "NFSVolume"
	VOL_TYPE_EMPTYDIR         = "EmptyDirVolume"
	VOL_TYPE_CONFIGFILEVOLUME = "ConfigFileVolume"
)

type Volume struct {
	Type                 string             `name:"Type"`
	Name                 string             `name:"Name"`
	NfsVolumePath        string             `name:"NFSVolume.Path"`
	NfsVolumeServer      string             `name:"NFSVolume.Server"`
	NfsVolumeReadOnly    requests.Boolean   `name:"NFSVolume.ReadOnly"`
	EmptyDirVolumeEnable requests.Boolean   `name:"EmptyDirVolume.Enable"`
	ConfigFileToPaths    []ConfigFileToPath `name:"ConfigFileVolume.ConfigFileToPath" type:"Repeated"`
}
