apiVersion: v1
kind: ServiceAccount
metadata:
  name: vk
  namespace: default

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vk
rules:
  - apiGroups:
      - ""
    resources:
      - "*"
    verbs:
      - "*"
  - apiGroups:
      - "coordination.k8s.io"
    resources:
      - "leases"
    verbs:
      - "*"

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: vk
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: vk
subjects:
  - kind: ServiceAccount
    name: vk
    namespace: default
