linter-settings:
  lll:
    line-length: 200

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - golint
    - goconst
    - goimports
    - unused
    - varcheck
    - deadcode
    - misspell

issues:
  exclude-use-default: false
  exclude:
    # EXC0001 errcheck: Almost all programs ignore errors on these functions and in most cases it's ok
    - Error return value of .((os\.)?std(out|err)\..*|.*Close|.*Flush|os\.Remove(All)?|.*print(f|ln)?|os\.(Un)?Setenv). is not checked

    # EXC0003 golint: False positive when tests are defined in package 'test'
    - func name will be used as test\.Test.* by other packages, and that stutters; consider calling this