linter-settings:
  lll:
    line-length: 200

run:
  skip-dirs:
    # This directory contains copy code from upstream kubernetes/kubernetes, skip it.
    - internal/kubernetes

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - golint
    - goconst
    - goimports
    - unused
    - varcheck
    - deadcode
    - misspell
    - nolintlint
    - gocritic

issues:
  exclude-use-default: false
  exclude:
    # EXC0001 errcheck: Almost all programs ignore errors on these functions and in most cases it's ok
    - Error return value of .((os\.)?std(out|err)\..*|.*Close|.*Flush|os\.Remove(All)?|.*print(f|ln)?|os\.(Un)?Setenv). is not checked
