run:
  timeout: 10m

linters:
  enable:
    - errcheck
    - staticcheck
    - unconvert
    - gofmt
    - goimports
    - ineffassign
    - govet
    - unused
    - misspell
    - gosec
    - copyloopvar
    - tenv # Detects using os.Setenv instead of t.Setenv since Go 1.17

linters-settings:
  lll:
    line-length: 200
  gosec:
    excludes:
      - G304
issues:
  exclude-dirs:
    # This directory contains copy code from upstream kubernetes/kubernetes, skip it.
    - internal/kubernetes
    # This is mostly copied from upstream, rather than fixing that code here just ignore the errors.
    - internal/podutils
  exclude-use-default: false
  exclude:
    # EXC0001 errcheck: Almost all programs ignore errors on these functions and in most cases it's ok
    - Error return value of .((os\.)?std(out|err)\..*|.*Close|.*Flush|os\.Remove(All)?|.*print(f|ln)?|os\.(Un)?Setenv). (is not checked|Errors unhandled)
