package eci

//Licensed under the Apache License, Version 2.0 (the "License");
//you may not use this file except in compliance with the License.
//You may obtain a copy of the License at
//
//http://www.apache.org/licenses/LICENSE-2.0
//
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.
//
// Code generated by Alibaba Cloud SDK Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

// Container is a nested struct in eci response
type Container struct {
	Name            string           `json:"Name" xml:"Name" position:"Query" name:"Name"`
	Image           string           `json:"Image" xml:"Image" position:"Query" name:"Image"`
	Memory          float64          `json:"Memory" xml:"Memory" position:"Query" name:"Memory"`
	Cpu             float64          `json:"Cpu" xml:"Cpu" position:"Query" name:"Cpu"   `
	RestartCount    int              `json:"RestartCount" xml:"RestartCount"`
	WorkingDir      string           `json:"WorkingDir" xml:"WorkingDir" position:"Query" name:"WorkingDir"`
	ImagePullPolicy string           `json:"ImagePullPolicy" xml:"ImagePullPolicy" position:"Query" name:"ImagePullPolicy"`
	Commands        []string         `json:"Commands" xml:"Commands" position:"Query" name:"Command"  type:"Repeated"`
	Args            []string         `json:"Args" xml:"Args" position:"Query" name:"Arg"  type:"Repeated"`
	PreviousState   ContainerState   `json:"PreviousState" xml:"PreviousState"`
	CurrentState    ContainerState   `json:"CurrentState" xml:"CurrentState"`
	VolumeMounts    []VolumeMount    `json:"VolumeMounts" xml:"VolumeMounts" position:"Query" name:"VolumeMount"  type:"Repeated"`
	Ports           []ContainerPort  `json:"Ports" xml:"Ports" position:"Query" name:"Port"  type:"Repeated"`
	EnvironmentVars []EnvironmentVar `json:"EnvironmentVars" xml:"EnvironmentVars" position:"Query" name:"EnvironmentVar"  type:"Repeated"`
}
