apiVersion: v1
kind: Pod
metadata:
  name: busyecho
spec:
  containers:
  - image: busybox
    command:
      - echo "Hello from container"
    imagePullPolicy: Always
    name: nginx
    resources:
      requests:
        memory: 1G
        cpu: 1
    ports:
    - containerPort: 80
      name: http
      protocol: TCP
    - containerPort: 443
      name: https
  dnsPolicy: ClusterFirst
  nodeName: virtual-kubelet
  tolerations:
  - key: azure.com/aci
    effect: NoSchedule
