apiVersion: v1
kind: Pod
metadata:
  name: nano
spec:
  containers:
  - image: microsoft/nanoserver:latest
    imagePullPolicy: Always
    command: ["powershell.exe", "-Command", "while ($true) { Sleep 5; Write-Host 'helloworld' }"]
    name: nanoserver
  dnsPolicy: Default
  restartPolicy: OnFailure
  nodeSelector:
    kubernetes.io/role: agent
    beta.kubernetes.io/os: windows
    type: virtual-kubelet
  automountServiceAccountToken: false
  tolerations:
  - key: virtual-kubelet.io/provider
    operator: Exists
  - key: azure.com/aci
    effect: NoSchedule
