apiVersion: v1
kind: Pod
metadata:
  name: nano
spec:
  containers:
  - image: microsoft/nanoserver:latest
    imagePullPolicy: Always
    command: ["powershell.exe", "-Command", "while ($true) { Sleep 5; Write-Host 'helloworld' }"]
    name: nanoserver
  dnsPolicy: Default
  restartPolicy: OnFailure
  nodeName: virtual-kubelet-myaciconnector-win
  automountServiceAccountToken: false
  tolerations:
  - key: azure.com/aci
    effect: NoSchedule
