apiVersion: v1
kind: Service
metadata:
  name: virtual-kubelet
  labels:
    app: virtual-kubelet
spec:
  type: ClusterIP
  ports:
  - port: 10250
    targetPort: kubelet
  selector:
    app: virtual-kubelet
